### PR TITLE
Fix Tiny Tiny RSS plugin

### PR DESCRIPTION
**Pull request by JKingweb**
The Tiny Tiny RSS plugin has been broken for a few months (since at least [May 4, 2017](https://git.tt-rss.org/git/tt-rss/commit/7c9b5a3fe40a641af1cb6003b03b2352576a0c4b)). This patch fixes it.

### CODE REVIEW

**Comment by jangernert** [comment]
Great work. Thank you!
Was the API version also bumped with the changes?

**Comment by JKingweb** [comment]
I don't know; I'd have to find where the API lever is defined. I'll check when I have some time, but I can tell you that the level is at 14 in my month-old installation. I should probably update it and make sure my fixes still work against the current commit. 

I noticed the breakage, by the way, because I'm working on implementing the API in [my own RSS server](https://code.mensbeam.com/MensBeam/arsse), and I'm keen on supporting FeedReader natively, with automated testing so things won't break.

**Comment by JKingweb** [comment]
I checked:

1. This patch still works with TT-RSS' head commit
2. The version (defined in `include/version.php`) was 17.4 before the changes to the label functions, and remains so today
3. The API level (defined in `classes/api.php`) was 14 before and remains so today.

**Comment by jangernert** [comment]
Hm, I wonder if the API versions jumped so quickly recently, or if I got the wrong number when I wrote the plugin :D 
Anyway, let's merge this.

**Comment by jangernert** [comment]
I saw your RSS server supports the nextcloud API. Shouldn't that work with FeedReader as well?

**Comment by JKingweb** [comment]
It should! I'm principally a Windows user, so I've not actually tried FeedReader yet, but other clients for NextCloud News seem to work fine.

**Pull request merged**
