### PR TITLE
Libvilistextum fuzzing

### PR DESCRIPTION
**Pull request by brendanlong**
We've been having a lot of trouble with libvilistextum but weren't able to reproduce it, so I decided to run it through american fuzzy lop and see if it could help.

It immediately found three infinite loops:

 - If an input ends with `&` or `<`, we will loop by reading the character and then pushing it back (fixed by "Don't put back EOF")
 - If there's an unclosed HTML tag, we loop infinitely on the EOF (fied by "Fix infinite loop in HTML tags")

AFL also found a few crashes but I wasn't able to reproduce them in gdb.

### CODE REVIEW

**Comment by brendanlong** [comment]
Related to #733, and possibly others (#715)

**Comment by brendanlong** [comment]
There's a crash if you have an HTML attribute with a very specific sequence of characters still. I think it has something to do with it being an invalid UTF-8 sequence but I haven't figured it out yet.

**Comment by brendanlong** [comment]
I put notes about how I ran this here: https://github.com/jangernert/FeedReader/blob/master/FUZZ_TESTING.md

**Comment by jangernert** [comment]
wow, this came out of nowhere. :+1:

**Pull request merged**
