### PR TITLE
Remove webkit2gtk vapi

### PR DESCRIPTION
**Pull request by jtojnar**
Introduced in aa6e6fba86f751004d1b5d52e6766a7b146abdae, it is not actually needed when the dependency is specified correctly – that is webkit2gtk-4.0, not WebKit2-4.0.

Closes: #593

### CODE REVIEW

**Comment by jangernert** [comment]
Uh oh, looks like the CI server is not recent enough and is missing the webkit menu entry creation from gaction.
@brendanlong do we have to revert this after all, or can we somehow use a more recent distibution as build environment?

**Comment by brendanlong** [comment]
I'll try moving us to Fedora 27

**Comment by jtojnar** [comment]
Fedora 26 should contain webkitgtk 2.18.4, which compiles for me on NixOS.

**Comment by jangernert** [comment]
@jtojnar I believe the vapi of webkitgtk is part of vala and so the vala version is the interesting here.

**Comment by jtojnar** [comment]
It builds fine even with vala 0.36.8.

**Comment by brendanlong** [comment]
Hmmm I can make a new image but the docker push isn't working:  #623

**Comment by brendanlong** [comment]
Oh maybe I got it..

**Comment by brendanlong** [comment]
Fixed with #623

**Comment by jangernert** [comment]
Nice!

**Pull request merged**
