### PR TITLE
Prepare for v2.4.0 release

### PR DESCRIPTION
**Pull request by brendanlong**
Releasing a fix for #763

### CODE REVIEW

**Comment by brendanlong** [comment]
Is this everything I need for a release?

**Comment by bilelmoussaoui** [comment]
It would be nice if you could update the flatpak manifest using the latest modifications we have in the flathub repository before pushing the update. Thanks!!

**Comment by brendanlong** [comment]
Oh I didn't realize we needed to copy changes from that repo into this one. I'll take a look.

**Comment by bilelmoussaoui** [comment]
We have the manifest on this repository for a clone/build/modify/run experience with GNOME Builder.

**Pull request merged**
