### PR TITLE
Fix for #712

### PR DESCRIPTION
**Pull request by asm0dey**

### CODE REVIEW

**Comment by brendanlong** [comment]
This changes fixes #712 for you?

@bilelmoussaoui Do you know if we made this change on purpose? I'm not sure what it does?

**Comment by asm0dey** [comment]
@brendanlong  yes

**Comment by asm0dey** [comment]
I'm sorry, I;m Java guy, not C/Vala/C++. I have absolutely no idea how does this fix work

**Comment by brendanlong** [comment]
Ok, thanks! I'll talk to @bilelmoussaoui and figure out what we were trying to do here.

**Pull request merged**
