### PR TITLE
Get rid of vilistextum

### PR DESCRIPTION
**Pull request by brendanlong**
See #712

Even with all of the improvements to libvilistextum, it still doesn't work right for several locales. This is a WIP to just remove vilistextum and replace it with glib's string.make_valid and [Gumbo](https://github.com/google/gumbo-parser/blob/master/examples/clean_text.cc).

### CODE REVIEW

**Comment by jangernert** [comment]
What baffles me is that these problems appeared for a lot of people only recently
I guess `make_valid()` doesn't handle html entities. Also vilistextum was used to convert html to plain text previews. Before I used html2text. But that was forgiving regarding invalid html and required the html to be written to disk. Then the html2text binary was spawned to parse the file.

edit: ah I see you're using "gumbo" (never heard of it)
does gumbo also work on *mostly* plain text? like I mentioned quite a lot of feeds put html entities in their headlines or summaries.

**Comment by brendanlong** [comment]
Yeah, I have no idea why libvilistextum stopped working. It seems like the problems started when we switched to meson, but we didn't change libvilistextum at that time. We did do a new release though, so I wonder if a lot of people were on much older versions?

I was trying to fix libvilistextum itself, but it seemed simpler to just replace it with two well-known libraries for the same thing.

I'll make sure Gumbo works for the HTML tag stripping before I merge this.

**Comment by jangernert** [comment]
I think the [planetKDE](https://planet.kde.org/rss20.xml) feed has html entities instead of ampersands in their titles. But most of the feeds I read behave nicely.

```
<title>KDAB at SIGGRAPH &#x2013; 2018</title>
```

btw: making steady progress with the [rust lib](https://gitlab.com/news-flash/news_flash_base). So if you get tired dealing with the poor decisions I made in the past in FeedReader (like vilistextum) you could hop over and prevent me from doing more of them in the new code base :D

**Comment by brendanlong** [comment]
It seems to handle this feed correctly:

screenshot from 2018-08-29 13-27-06

I was having issues with it for a while until I realized the local RSS plugin is apparently producing invalid characters (it's converting en dash to \x0013 when it should be \x2013). I'm looking into that piece but the rest is good..

**Comment by brendanlong** [comment]
I don't understand what's wrong with the local plugin. For some reason the RSS parser is turning `&#x2013;` into `\x00\0x13` instead of `\x20\x13`. I can confirm that it was doing this before I replaced vilistextum though:

screenshot from 2018-08-29 13-51-25

**Comment by jangernert** [comment]
I wouldn't worry about it right now.

**Comment by brendanlong** [comment]
I fixed the flatpak and prepared a new release. I'll merge when the build finishes.

**Comment by asm0dey** [comment]
@brendanlong I've found exact commit where hyerogliphs started appearing. On same DB one version doesn't show them and next commit shows. I don't know if there was something about library changes.

**Comment by brendanlong** [comment]
@asm0dey What commit was that?

**Comment by asm0dey** [comment]
@brendanlong https://github.com/jangernert/FeedReader/issues/712#issuecomment-412995514

**Comment by asm0dey** [comment]
@brendanlong https://github.com/jangernert/FeedReader/issues/712#issuecomment-414050816

**Comment by brendanlong** [comment]
@asm0dey Are you still running into the encoding issue (or a related issue)?

**Comment by asm0dey** [comment]
@brendanlong nop, as I've witten in #712 :) And thank you again

**Pull request merged**
