### PR TITLE
Bazqux

### PR DESCRIPTION
**Pull request by kanishkablack**

### CODE REVIEW

**Comment by kanishkablack** [comment]
Most of the functionality is working

**Comment by kanishkablack** [comment]
supportCategories()

**Comment by jangernert** [comment]
what do you mean by "Most of the functionality is working". What is not working? And have you tested each and every function of the back-end yourself?

**Comment by kanishkablack** [comment]
Yep, testing all the functionality

Adding/Editing/Delete Feed
Adding/Editing/Delete Category
Adding/Editing/Delete Tag

**Comment by kanishkablack** [comment]
Excuse my bad english, what mean about it is, I tested all the functions, i might have missed which are specific to this service.

All the general functions are working

Adding/Editing/Delete Feed
Adding/Editing/Delete Category
Adding/Editing/Delete Tag

Mark as Read/Unread/Star/Unstart for Articles
Add/Removing Tag for Article
Mark as Read for categories.

**Comment by jangernert** [comment]
fixed up and merged with commit 3802cb5428e8507d33df487364252270685e0e9a

**Pull request closed without merging**
