### PR TITLE
TheOldReader and FeedHQ

### PR DESCRIPTION
**Pull request by kanishkablack**
Hai
i have added code to integrate both TheOldreader and FeedHQ

Few things still incomplete, which are out of my limits.

Icons for both the services.
<del>Disable tag for Article view.<del>

And Bazqux integration started out, most the code is optimised few API end points are to be adjusted. 
Login to bazqux is commented.

EDIT: Disable tag Button in Article view completed. ( https://github.com/jangernert/FeedReader/pull/147/commits/8878a85eb44a85ba7a92324e1412ef2ee76fcb5b  )

### CODE REVIEW

**Comment by jangernert** [comment]
Uhhhm, why are you pull all your branches together to one single pull request? It would be much easier to evaluate each and every back-end if you propose them separately.
Also, why is "Disable tag for Article view" "out of limits"?

**Comment by kanishkablack** [comment]
ah, i accidentally deleted branches, all i have is master repo. I will look into that once.

"out of limits", correction, "its out of my limits" - ( mistake while typing )

"Disable tag for article view", it disables the tags in categories



but for some strange reasons, it will appears in article view ( it might missed a step )
i have concentrated on back-end daemon most of the time and i didn't have time to go through the UI part of API.

**Comment by jangernert** [comment]
The issue with the tag-button should be resolved now

**Comment by kanishkablack** [comment]
@jangernert Its been working apt now.

But i found a small bug/issue. please have a look at it

https://vimeo.com/172292669

Tested in Feedly, Theoldreader, inoreader

**Comment by jangernert** [comment]
I think I fixed the crash. Can you confirm on your PC?
I also drew some old-reader icons in Inkscape and added them to the repository.
Not sure if feedhq even has a official logo.

**Comment by kanishkablack** [comment]
- crash is fixed.
- Icons are updated
- FeedHQ doesn't have any logo yet.

**Comment by jangernert** [comment]
So are you going to split up the pull-request?

**Comment by kanishkablack** [comment]
i didn't have the independent branches.

**Comment by jangernert** [comment]
Didn't you say you want to split up the code again?

**Comment by kanishkablack** [comment]
i didn't have time to do it

**Comment by jangernert** [comment]
As you might have noticed I refactored all the back-ends to plugins using libpeas.
This should make it way easier to add new services like this.

https://github.com/jangernert/FeedReader/tree/master/plugins/demo
https://github.com/jangernert/FeedReader/wiki/Add-new-Backend

**Comment by kanishkablack** [comment]
Will try to update( in my free time )

**Comment by kanishkablack** [comment]
didn't have time to see the code.

@jangernert you took an great effort to work with plugins

**Pull request closed without merging**
