### PR TITLE
Alot of flatpak changes

### PR DESCRIPTION
**Pull request by jscurtu**
- FeedReader now available as flatpak online repository. 
- Uses Amazon AWS S3 (lets see how much that cost me :-/ )
- Package is signed and published (currently master only, stable is in the works)
- Makefile based on alexlarson's approch.

source: https://blogs.gnome.org/alexl/2017/02/10/maintaining-a-flatpak-repository/

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
@jscurtu There's some conflicts with the Makefile? We hope we can attract more guys on BountySource to get some financial help for those kind of stuff :)

**Comment by jscurtu** [comment]
Shoot.. how do I resolve this now

**Comment by jangernert** [comment]
I don't think the patches are needed any more. The HOME envvar was fixed in 05530fbf53c82a40bd3e89906b9c830a8665f1f1 and the appdata installation should just be merged to master ;) Or is this only for the old stable version 1.6.2?
Since webkitgtk 2.14.4 is finally out I wanted to release 2.0 as stable anyways.

**Comment by jscurtu** [comment]
its for the old .. if the release is near then I will remove them ..

**Comment by jscurtu** [comment]
let me know when your ready.. this gives me the oppertunity branch flatpak repo to stable instead of master. 
I was not able to create a stable branch anyway due to 1.6.2 to 2.0 changes with the dbus naming.

**Comment by jangernert** [comment]
Bumped version to 2.0, added you to contributor list, pushed everything to stable-branch and created a new tag.
Now I think only the website needs to be updated.

**Comment by jangernert** [comment]
Okay, I guess we're all done. If I forgot to update something feel free to do it.
I'll wait 1-2 days to give maintainers a chance to update their packages. Then I'll do some posts on G+ and reddit. Also feel free to spread the word on the interwebz :)

**Comment by jscurtu** [comment]
Flatpak repro is already sync'd, live and pointing to stable .. tested and works.. :-)

**Comment by jscurtu** [comment]
there, PR accepted :-) .. FeedReader is now listed on official http://flatpak.org/apps.html

grafik

cc @jangernert @bil-elmoussaoui

**Comment by bil-elmoussaoui** [comment]
@jscurtu Great job!!!!

**Pull request merged**
