### PR TITLE
cmake to meson

### LINKED ISSUE #514: Port from CMake to Meson
Meson is a "new" build system. Which supports GNOME Natively with a Gnome plugin. And also has 0 dependencies. It's a lot faster than Autotools and more readable by humans. I have been converting few projects lately to use Meson instead.

I can work on this if everyone agrees. The build time will be much shorter.

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
I finally start working on implementing the cmake-meson switch.

Closes #514 #540 

All the libraries compile correctly.

Still few stuff to do:
- [x] Add share/backend plugins meson.build file
- [ ] Correct web extensions not compiling due to a non-found header file
```
libraries/WebExtension/webextension@sha/webextension.c:8:10: fatal error: webkit2/webkit-web-extension.h: No such file or directory
 #include "webkit2/webkit-web-extension.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
- [x] libIvy not detected at all :(
- [x] Update Linguas / Potfiles 
- [x] Add the post install script

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
@jangernert @brendanlong 
I'm having a little issue here, i couldn't get meson to detect libIvy, as the vapi is generated later on the build and i don't think there's a way to tell meson/ninja what should be built at first (i'm going to ask on iirc and see if there's a way to fix it)
otherwise, we can generate the vapi and put it on the vapi dir which should fix the issue 👍

**Comment by bil-elmoussaoui** [comment]
A lot of progress was made in my latest commits; the only issue i'm struggling with is compiling the web extension :) i'm working right now on getting a build file for all the plugins 👍

**Comment by bil-elmoussaoui** [comment]
Update: the latest meson version didn't fix the issue we had yet... So we should wait until the next version! I'm going to polish this more and push a fix upstream to meson so we are sure to have this ready for the next version

**Comment by jangernert** [comment]
Meson releases seem to be pretty frequent, so that seems fine :)

**Comment by brendanlong** [comment]
Is there anything special I need to do to run this? I tried and get:

```
$ meson build
The Meson build system
Version: 0.43.0
Source dir: /home/blong/workspace/FeedReader
Build dir: /home/blong/workspace/FeedReader/build
Build type: native build
Project name: FeedReader
Native C compiler: ccache cc (gcc 7.2.1)
Native Vala compiler: valac (valac 0.36.5)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.3.9)
Native dependency gdk-pixbuf-2.0 found: YES 2.36.9
Native dependency gee-0.8 found: YES 0.20.0
Native dependency glib-2.0 found: YES 2.52.3
Native dependency goa-1.0 found: YES 3.24.4
Native dependency gstreamer-1.0 found: YES 1.12.3
Native dependency gstreamer-pbutils-1.0 found: YES 1.12.3
Native dependency gtk+-3.0 found: YES 3.22.21
Native dependency json-glib-1.0 found: YES 1.2.6
Library libcurl found: YES
Native dependency libnotify found: YES 0.7.7
Native dependency libpeas-1.0 found: YES 1.20.0
Native dependency libsecret-1 found: YES 0.18.5
Native dependency libsoup-2.4 found: YES 2.58.2
Native dependency libxml-2.0 found: YES 2.9.4
Library linux found: YES
Library posix found: YES
Native dependency rest-0.7 found: YES 0.8.0
Native dependency sqlite3 found: YES 3.20.1
Native dependency webkit2gtk-4.0 found: YES 2.18.0
Configuring config.h using configuration
Message: TODO: Compiling resources
Native dependency glib-2.0 found: YES 2.52.3
Message: TODO: Making a .desktop file
Message: TODO: Preparing appdata
Library gd-1.0 found: YES
Library gtkimageview found: YES
Library libvilistextum found: YES
Library m found: YES
Configuring Constants.vala using configuration
WARNING: The variable(s) 'GIT_SHA1' in the input file Constants.vala.in are not present in the given configuration data
Message: Backend Plugin: bazqux is ON
Message: Backend Plugin: feedbin is ON
Message: Backend Plugin: feedhq is ON
Message: Backend Plugin: feedly is ON
Message: Backend Plugin: fresh is ON
Message: Backend Plugin: inoreader is ON
Message: Backend Plugin: local is ON
Library rss-glib-1.0 found: YES
Message: Backend Plugin: oldreader is ON
Message: Backend Plugin: owncloud is ON
Message: Backend Plugin: ttrss is ON
Message: Share Plugin: Browser is ON
Message: Share Plugin: Email is ON
Message: Share Plugin: Instapaper is ON
Message: Share Plugin: Pocket is ON
Message: Share Plugin: Telegram is ON
Message: Share Plugin: Twitter is ON
Message: Share Plugin: Wallabag is ON
Program meson_post_install.py found: YES (/home/blong/workspace/FeedReader/meson_post_install.py)
Build targets in project: 68
Found ninja-1.8.2 at /usr/bin/ninja

$ ninja -C build
ninja: Entering directory `build'
ninja: error: 'FeedReader@sha/meson-generated_FavIconCache.c.o', needed by 'feedreader', missing and no known rule to make it
```

**Comment by brendanlong** [comment]
This commit made the build able to configure for me: https://github.com/brendanlong/FeedReader/commit/96cf6ecfd781b26306d920c56742062accc42910

Using `link_with` instead of `dependencies` for local dependencies.

**Comment by bil-elmoussaoui** [comment]
Ah! alright, can you push that to this branch? I will try to work on this soon to finish up everything 👍

**Comment by brendanlong** [comment]
Ok, I pushed it. I still get errors about `Constants.c` not existing, and not being able to find `Gd` though :(

**Comment by bil-elmoussaoui** [comment]
One sec, i will try this right now

**Comment by bil-elmoussaoui** [comment]
I think this patch should fix the libgd not being found

**Comment by bil-elmoussaoui** [comment]
@brendanlong We can easily avoid that by moving the stuff that doesn't require the build system to a constants.vala and put it in the source code file. And for the rest, we use already the config.h file! Not sure if that will work, but i will give it a try right now

**Comment by bil-elmoussaoui** [comment]
Fixed few issues, but there's still some more :/ 
I will see what i can do tomorrow

**Comment by brendanlong** [comment]
Cool thanks! I'm getting really tired of fighting with CMake so I'm pretty excited about this :D

**Comment by bil-elmoussaoui** [comment]
I have some free time this weekend and i will work on finishing this! 👍

**Comment by jangernert** [comment]
closed in favor of #641

**Pull request closed without merging**
