### PR TITLE
Fix parsing date on non English locales

### LINKED ISSUE #652: Date of feed items are not detected on some locales
Using the local backend, the date of the feed items are not detected, and always the current time is shown.

Steps to reproduce:

1. Start feedreader with German or Hungarian locale, e.g.: `LANG=de_DE.UTF-8 feedreader`
2. Switch to the local backend.
3. Add some feeds.
4. See that the date of each items are the current time instead of the date provided by the feed author.

Tested with the latest git version as of 2018.04.19.

### PR DESCRIPTION
**Pull request by City-busz**
Fixes #652

### CODE REVIEW

**Comment by City-busz** [comment]
> I was hoping to find an RFC 822 date parser but I can't find a pre-existing one. If I have time I'll write to write one in Vala.

That would be great. The currently used [GLib.Time](https://valadoc.org/glib-2.0/GLib.Time.html) ignores timezone, so the stored time is shifted.

**Comment by brendanlong** [comment]
See #658

**Comment by brendanlong** [comment]
@City-busz This should be fixed by 78d7ced862aa491d64d9b5f135b2ba2d893b79d1. Let me know if you have any other problems with this (or test cases to add: https://github.com/jangernert/FeedReader/blob/master/plugins/backend/local/TestLocalRSS.vala)

**Comment by City-busz** [comment]
It works as expected. Thanks!

However, it breaks parallel build (make -j8) somehow:
`make[2]: *** No rule to make target 'FeedReader.vapi', needed by 'plugins/backend/local/local_target_valac.stamp'.  Stop.`

**Pull request closed without merging**
