### PR TITLE
Do a 2.1 (or 3.0) release

### PR DESCRIPTION
**Pull request by brendanlong**
I'll tag this once we merge.

Do I need to do anything in particular to make Flatpak work?

I can write up a release notes thing.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I have been working on flatpaking few apps recently. I'm going to update the flatpak manifest tomorrow and push the updates upstream to flathub

**Comment by jscurtu** [comment]
If you need any help let me know .. I am still here :-)

**Comment by bilelmoussaoui** [comment]
Created a PR. Once it's merged, can you pull the modifications and update the version number on the meson build file and we can tag it :+1:

**Comment by bilelmoussaoui** [comment]
Once everything is merged to master; Can you also run 
```
meson builddir
ninja -C builddir test
ninja -C builddir feedreader-update-po 
```
This will update the po files and the pot files too ! :+1:

**Comment by bilelmoussaoui** [comment]
Updated the po & pot files. Can anyone create a new release tag?

**Comment by jangernert** [comment]
@bilelmoussaoui done. But still need to investigate all the changes and write up a small changelog.

**Comment by bilelmoussaoui** [comment]
Does it include the latest pot/po modifications? they are only on master I guess :/

**Comment by brendanlong** [comment]
I wrote up some changes here: https://github.com/jangernert/FeedReader/releases/tag/v2.2

Add more if I missed anything!

@bilelmoussaoui We could do a v2.2.1 with the pot/po's?

**Comment by bilelmoussaoui** [comment]
Yeah that would be better! I have already merged the pot/po's to stable!

**Pull request merged**
