### PR TITLE
Fix gettext translations

### PR DESCRIPTION
**Pull request by horosgrisa**

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Can you only modify the FeedReader.pot? the translations are updated automatically in Transifex

**Comment by horosgrisa** [comment]
@bil-elmoussaoui Check now

**Comment by bil-elmoussaoui** [comment]
Good just need to remove the ru.pot from the commit (and update the translations on Transifex)

**Comment by jangernert** [comment]
oh, already build a new pot file and pushed it to master
so no need to merge this anymore
now you can submit the translations through transifex ;)

**Pull request closed without merging**
