### PR TITLE
v2.9.0 release

### PR DESCRIPTION
**Pull request by brendanlong**

### CODE REVIEW

**Comment by brendanlong** [comment]
@bilelmoussaoui I just wanted to run the changelog by you since you did most of the commits this time

**Comment by bilelmoussaoui** [comment]
Can we wait a bit as I'm trying to get some nice new screenshots

**Comment by bilelmoussaoui** [comment]
Ideally, I would like to have both #862 #863 before 2.9.0 release.

**Comment by brendanlong** [comment]
The main fix I want to release is 193ea1291c6135f5357e6a9a340f323b49defbad but I'll just backport it to a 2.8.2 release

**Comment by brendanlong** [comment]
We'll need to mention #881 in the changelog when we the next release

**Comment by bilelmoussaoui** [comment]
We can easily just set correct milestones here on Github so we can have a proper way to find the changelog of a specific version. We can even be a bit lazier and create a simple script that does that for us :)

**Comment by brendanlong** [comment]
Ah that's useful: https://github.com/jangernert/FeedReader/milestone/10

**Comment by brendanlong** [comment]
I'm doing a v2.9.0 release and moved the remaining stuff to v2.10.0

**Comment by bilelmoussaoui** [comment]
Alright, thanks for taking care of this :+1:

**Pull request merged**
