### PR TITLE
Updated Ukrainian translation

### PR DESCRIPTION
**Pull request by dankor**

### CODE REVIEW

**Comment by jangernert** [comment]
Thank you for your efforts. But I think transfix would be a better place to contribute translations ;)

**Comment by dankor** [comment]
I've joined the team, but can't contribute there. Last po file updated 9 moths ago, so, I decided to make a pull request instead. Thanks.

**Comment by bil-elmoussaoui** [comment]
I will update the PO files in few hours! I accepted your request to join the translation team, you can contribute right now:) 
I'm going to close this to keep translations things updated only on Transifex. Thanks

**Comment by dankor** [comment]
Thank you! I've uploaded my translation there.

**Pull request closed without merging**
